/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces.listas;

import banco.DAOfuncionario;
import base.Funcionario;
import base.Main;
import interfaces.HomeGerente;
import java.util.List;

/**
 *
 * @author Jorge
 */
public class ListarFuncionarios extends javax.swing.JPanel {

    /**
     * Creates new form ListarFuncionarios
     */
    private DAOfuncionario dao;
    private String[][] objects;
    private String[] colunas = {"ID", "Nome", "CPF", "Endereco", "Telefone", "Gênero", "Nascimento", "Salario", "Admissao", "CargaH", "Filial"};
    
    public ListarFuncionarios() {
        dao = new DAOfuncionario();
        loadElements();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtList = new javax.swing.JTable(this.objects,this.colunas);
        bttVoltar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel1.setText("Lista de Funcionarios");

        jtList.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(jtList);

        bttVoltar.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        bttVoltar.setText("Voltar");
        bttVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(bttVoltar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bttVoltar)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bttVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttVoltarActionPerformed
        this.setVisible(false);
        Main.janela.remove(this);
        Main.janela.add(new HomeGerente());
        Main.janela.setVisible(true);
    }//GEN-LAST:event_bttVoltarActionPerformed
    
    private void loadElements(){
        List<Funcionario> list = dao.recuperaFuncionarios();
        this.objects = new String[list.size()][11];
        int i = 0;
        for(Funcionario fun: list){
            this.objects[i][0] = String.valueOf(fun.getCodFunc());
            this.objects[i][1] = fun.getNome();
            this.objects[i][2] = fun.getCpf();
            this.objects[i][3] = fun.getEndereco();
            this.objects[i][4] = fun.getTelefone();
            this.objects[i][5] = String.valueOf(fun.getGenero());
            this.objects[i][6] = fun.getNascimento();
            this.objects[i][7] = "RS "+ String.valueOf(fun.getSalario());
            this.objects[i][8] = fun.getAdmissao();
            this.objects[i][9] = String.valueOf(fun.getCargaH());
            this.objects[i][10] = String.valueOf(fun.getCodFilial());
            i++;
        }
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtList;
    // End of variables declaration//GEN-END:variables
}
