/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces.listas;

import banco.DAOveiculo;
import base.Main;
import base.Veiculo;
import interfaces.HomeGerente;
import java.util.List;

/**
 *
 * @author Jorge
 */
public class ListarVeiculos extends javax.swing.JPanel {

    /**
     * Creates new form ListarVeiculos
     */
    private DAOveiculo dao;
    private String[][] objects;
    private String[] colunas = {"ID", "Chassi", "Placa", "Modelo", "Cor", "Ano", "Filial"};
    
    public ListarVeiculos() {
        dao = new DAOveiculo();
        loadElements();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtList = new javax.swing.JTable(this.objects,this.colunas);
        bttVoltar1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel1.setText("Lista de Veiculos");

        jtList.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(jtList);

        bttVoltar1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        bttVoltar1.setText("Voltar");
        bttVoltar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttVoltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttVoltar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(bttVoltar1)
                .addContainerGap(269, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(234, 234, 234))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bttVoltar1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bttVoltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttVoltar1ActionPerformed
        this.setVisible(false);
        Main.janela.remove(this);
        Main.janela.add(new HomeGerente());
        Main.janela.setVisible(true);
    }//GEN-LAST:event_bttVoltar1ActionPerformed

    private void loadElements(){
        List<Veiculo> list = dao.recuperaVeiculos();
        this.objects = new String[list.size()][7];
        int i = 0;
        for(Veiculo vei: list){
            this.objects[i][0] = String.valueOf(vei.getCodVei());
            this.objects[i][1] = vei.getChassi();
            this.objects[i][2] = vei.getPlaca();
            this.objects[i][3] = vei.getModelo();
            this.objects[i][4] = vei.getCor();
            this.objects[i][5] = vei.getAno();
            this.objects[i][6] = String.valueOf(vei.getCodFilial());
            i++;
        }
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttVoltar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtList;
    // End of variables declaration//GEN-END:variables
}
