/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import interfaces.listas.ListarCliente;
import interfaces.edicoes.Devolucao;
import interfaces.edicoes.EditarCliente;
import interfaces.cadastros.CadastroCliente;
import interfaces.cadastros.CadAluguel;
import base.Main;
import base.Vendedor;
import interfaces.listas.ListarAlugueis;

/**
 *
 * @author Jorge
 */
public class HomeVendedor extends javax.swing.JPanel {

    /**
     * Creates new form HomeVendedor
     */
    private Vendedor vendedor;
    public HomeVendedor(Vendedor vendedor) {
        this.vendedor = vendedor;
        System.out.println(vendedor.getCodVend());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bttSair = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bttCadastrarC = new javax.swing.JButton();
        bttListarC = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        bttEditarC = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bttAlugar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        bttDevolver = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        bttListar = new javax.swing.JButton();

        jTabbedPane1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel1.setText("Bem Vindo ao SisCar");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/outros/carros.png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(592, 383));

        bttSair.setText("Sair");
        bttSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSairActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        jLabel29.setText("Logado como Vendedor");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bttSair)
                .addGap(20, 20, 20))
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel29)
                .addGap(235, 235, 235))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(bttSair))
                .addGap(4, 4, 4)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel29)
                .addGap(7, 7, 7))
        );

        jTabbedPane1.addTab("Home", jPanel1);

        jLabel3.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel3.setText("Gerenciamento Clientes");

        jLabel4.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel4.setText("Cadastrar");

        jLabel5.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel5.setText("Listar");

        bttCadastrarC.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        bttCadastrarC.setText("Cadastrar");
        bttCadastrarC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttCadastrarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCadastrarCActionPerformed(evt);
            }
        });

        bttListarC.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        bttListarC.setText("Listar");
        bttListarC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttListarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttListarCActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel6.setText("Editar");

        bttEditarC.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        bttEditarC.setText("Editar");
        bttEditarC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttEditarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttEditarCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(132, 132, 132))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(bttCadastrarC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bttListarC)
                .addGap(114, 114, 114))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(bttEditarC)))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel3)
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttCadastrarC)
                    .addComponent(bttListarC))
                .addGap(50, 50, 50)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bttEditarC)
                .addContainerGap(184, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Clientes", jPanel2);

        jLabel7.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel7.setText("Gerenciamento dos Alugueis");

        jLabel8.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel8.setText("Alugar");

        bttAlugar.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        bttAlugar.setText("Alugar");
        bttAlugar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttAlugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAlugarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel9.setText("Devolver");

        bttDevolver.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        bttDevolver.setText("Devolver");
        bttDevolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttDevolverActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel10.setText("Listar");

        bttListar.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        bttListar.setText("Listar");
        bttListar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(141, 141, 141))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addComponent(jLabel10))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addComponent(bttListar)))
                        .addGap(276, 276, 276))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(bttAlugar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bttDevolver)
                        .addGap(124, 124, 124))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jLabel7)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel7)
                .addGap(54, 54, 54)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttAlugar)
                    .addComponent(bttDevolver))
                .addGap(47, 47, 47)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bttListar)
                .addContainerGap(199, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Alugueis", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bttSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSairActionPerformed
        this.setVisible(false);
        Main.janela.remove(this);
        Main.janela.add(new Login());
        Main.janela.setVisible(true);
    }//GEN-LAST:event_bttSairActionPerformed

    private void bttCadastrarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCadastrarCActionPerformed
        this.setVisible(false);
        Main.janela.remove(this);
        Main.janela.add(new CadastroCliente(1,this.vendedor));
        Main.janela.setVisible(true);
    }//GEN-LAST:event_bttCadastrarCActionPerformed

    private void bttAlugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttAlugarActionPerformed
        this.setVisible(false);
        Main.janela.remove(this);
        Main.janela.add(new CadAluguel(this.vendedor));
        Main.janela.setVisible(true);
    }//GEN-LAST:event_bttAlugarActionPerformed

    private void bttDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttDevolverActionPerformed
        this.setVisible(false);
        Main.janela.remove(this);
        Main.janela.add(new Devolucao(this.vendedor));
        Main.janela.setVisible(true);
    }//GEN-LAST:event_bttDevolverActionPerformed

    private void bttEditarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttEditarCActionPerformed
        this.setVisible(false);
        Main.janela.remove(this);
        Main.janela.add(new EditarCliente(1,this.vendedor));
        Main.janela.setVisible(true);
    }//GEN-LAST:event_bttEditarCActionPerformed

    private void bttListarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttListarCActionPerformed
        this.setVisible(false);
        Main.janela.remove(this);
        Main.janela.add(new ListarCliente(1,this.vendedor));
        Main.janela.setVisible(true);
    }//GEN-LAST:event_bttListarCActionPerformed

    private void bttListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttListarActionPerformed
        this.setVisible(false);
        Main.janela.remove(this);
        Main.janela.add(new ListarAlugueis(this.vendedor));
        Main.janela.setVisible(true);
    }//GEN-LAST:event_bttListarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttAlugar;
    private javax.swing.JButton bttCadastrarC;
    private javax.swing.JButton bttDevolver;
    private javax.swing.JButton bttEditarC;
    private javax.swing.JButton bttListar;
    private javax.swing.JButton bttListarC;
    private javax.swing.JButton bttSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
