/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import base.Main;

/**
 *
 * @author Jorge
 */
public class Login extends javax.swing.JPanel {

    /**
     * Creates new form TelaLogin
     */
    public Login() {
        initComponents();
        jcbAdm.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfUsuario = new javax.swing.JTextField();
        bttEntrar = new javax.swing.JButton();
        bttRecuperarSenha = new javax.swing.JButton();
        jpfSenha = new javax.swing.JPasswordField();
        jcbAdm = new javax.swing.JCheckBox();
        jcbGer = new javax.swing.JCheckBox();
        jcbVen = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        bttAddUsuario = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Tela de Login", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monospaced", 0, 14))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel2.setText("Usuário:");

        jLabel3.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel3.setText("Senha:");

        jtfUsuario.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N

        bttEntrar.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        bttEntrar.setText("Entrar");
        bttEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttEntrarActionPerformed(evt);
            }
        });

        bttRecuperarSenha.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        bttRecuperarSenha.setText("Recuperar Senha?");

        jpfSenha.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N

        jcbAdm.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jcbAdm.setText("Administrador");
        jcbAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAdmActionPerformed(evt);
            }
        });

        jcbGer.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jcbGer.setText("Gerente");
        jcbGer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbGerActionPerformed(evt);
            }
        });

        jcbVen.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jcbVen.setText("Vendedor");
        jcbVen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbVenActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel4.setText("Logar como:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bttRecuperarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jtfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jpfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jcbAdm)
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(16, 16, 16))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jcbGer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jcbVen)
                                .addGap(28, 28, 28)))))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(bttEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jpfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bttRecuperarSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbAdm)
                    .addComponent(jcbGer)
                    .addComponent(jcbVen))
                .addGap(18, 18, 18)
                .addComponent(bttEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        bttAddUsuario.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        bttAddUsuario.setText("+");
        bttAddUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAddUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bttAddUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bttAddUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bttAddUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttAddUsuarioActionPerformed
        this.setVisible(false);
        Main.janela.remove(this);
        Main.janela.add(new LoginRoot());
        Main.janela.setVisible(true);
    }//GEN-LAST:event_bttAddUsuarioActionPerformed

    private void bttEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttEntrarActionPerformed
        if(jcbAdm.isSelected()){
            this.setVisible(false);
            Main.janela.remove(this);
            Main.janela.add(new HomeAdministrador());
            Main.janela.setVisible(true);
        }
        else if(jcbGer.isSelected()){
            this.setVisible(false);
            Main.janela.remove(this);
            Main.janela.add(new HomeGerente());
            Main.janela.setVisible(true);
        }
        else{
            this.setVisible(false);
            Main.janela.remove(this);
            Main.janela.add(new HomeVendedor());
            Main.janela.setVisible(true);
        }
    }//GEN-LAST:event_bttEntrarActionPerformed

    private void jcbAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAdmActionPerformed
        jcbGer.setSelected(false);
        jcbVen.setSelected(false);
    }//GEN-LAST:event_jcbAdmActionPerformed

    private void jcbGerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbGerActionPerformed
        jcbAdm.setSelected(false);
        jcbVen.setSelected(false);
    }//GEN-LAST:event_jcbGerActionPerformed

    private void jcbVenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbVenActionPerformed
        jcbAdm.setSelected(false);
        jcbGer.setSelected(false);
    }//GEN-LAST:event_jcbVenActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttAddUsuario;
    private javax.swing.JButton bttEntrar;
    private javax.swing.JButton bttRecuperarSenha;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox jcbAdm;
    private javax.swing.JCheckBox jcbGer;
    private javax.swing.JCheckBox jcbVen;
    private javax.swing.JPasswordField jpfSenha;
    private javax.swing.JTextField jtfUsuario;
    // End of variables declaration//GEN-END:variables
}
